#!/bin/python3

import subprocess as sp
import socket
from colored import style, fore

jctl = sp.Popen(["journalctl", "-u", "svscode"], stdout=sp.PIPE, stderr=sp.PIPE)
out, err = jctl.communicate()
host = out.split(b"Web UI available at ")[-1].split(b"\n")[0].decode()

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("8.8.8.8", 80))
ip_addr = s.getsockname()[0]
s.close()

print(f"{fore.CYAN}VSCode{style.RESET}:", host.replace("localhost", ip_addr))